"""Merge UserXp table into User

Revision ID: b6ec25aed6d4
Revises: e0494913a70e
Create Date: 2024-10-27 10:44:40.232954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6ec25aed6d4'
down_revision: Union[str, None] = 'e0494913a70e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_xp_user_index', table_name='user_xp')
    op.drop_table('user_xp')
    op.drop_index('case_case_id_index', table_name='case')
    op.drop_index('case_user_id_index', table_name='case')
    op.create_index(op.f('ix_case_case_id'), 'case', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_user_id'), 'case', ['user_id'], unique=False)
    op.drop_index('filter_word_word_index', table_name='filter_word')
    op.create_index(op.f('ix_filter_word_phrase'), 'filter_word', ['phrase'], unique=False)
    op.drop_index('meme_name_index', table_name='meme')
    op.create_index(op.f('ix_meme_phrase'), 'meme', ['phrase'], unique=False)
    op.drop_index('raid_phrase_word_index', table_name='raid_phrase')
    op.create_index(op.f('ix_raid_phrase_phrase'), 'raid_phrase', ['phrase'], unique=False)
    op.drop_index('sticky_role_user_id_index', table_name='sticky_role')
    op.create_index(op.f('ix_sticky_role_user_id'), 'sticky_role', ['user_id'], unique=False)
    op.drop_index('tag_name_index', table_name='tag')
    op.create_index(op.f('ix_tag_phrase'), 'tag', ['phrase'], unique=False)
    op.drop_index('tag_button_tag_name_index', table_name='tag_button')
    op.create_index(op.f('ix_tag_button_tag_name'), 'tag_button', ['tag_name'], unique=False)
    op.add_column('user', sa.Column('xp', sa.BigInteger(), nullable=True))
    op.add_column('user', sa.Column('level', sa.BigInteger(), nullable=True))
    op.add_column('user', sa.Column('is_xp_frozen', sa.Boolean(), nullable=True))
    op.drop_index('user_user_id_index', table_name='user')
    op.create_index(op.f('ix_user_user_id'), 'user', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_user_id'), table_name='user')
    op.create_index('user_user_id_index', 'user', ['user_id'], unique=False)
    op.drop_column('user', 'is_xp_frozen')
    op.drop_column('user', 'level')
    op.drop_column('user', 'xp')
    op.drop_index(op.f('ix_tag_button_tag_name'), table_name='tag_button')
    op.create_index('tag_button_tag_name_index', 'tag_button', ['tag_name'], unique=False)
    op.drop_index(op.f('ix_tag_phrase'), table_name='tag')
    op.create_index('tag_name_index', 'tag', ['phrase'], unique=False)
    op.drop_index(op.f('ix_sticky_role_user_id'), table_name='sticky_role')
    op.create_index('sticky_role_user_id_index', 'sticky_role', ['user_id'], unique=False)
    op.drop_index(op.f('ix_raid_phrase_phrase'), table_name='raid_phrase')
    op.create_index('raid_phrase_word_index', 'raid_phrase', ['phrase'], unique=False)
    op.drop_index(op.f('ix_meme_phrase'), table_name='meme')
    op.create_index('meme_name_index', 'meme', ['phrase'], unique=False)
    op.drop_index(op.f('ix_filter_word_phrase'), table_name='filter_word')
    op.create_index('filter_word_word_index', 'filter_word', ['phrase'], unique=False)
    op.drop_index(op.f('ix_case_user_id'), table_name='case')
    op.drop_index(op.f('ix_case_case_id'), table_name='case')
    op.create_index('case_user_id_index', 'case', ['user_id'], unique=False)
    op.create_index('case_case_id_index', 'case', ['case_id'], unique=False)
    op.create_table('user_xp',
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('xp', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('level', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('is_xp_frozen', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name='user_xp_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', name='user_xp_pkey')
    )
    op.create_index('user_xp_user_index', 'user_xp', ['user_id'], unique=False)
    # ### end Alembic commands ###
