"""Create initial database structure

Revision ID: 0e74907af7d5
Revises: 
Create Date: 2024-10-18 23:06:10.120326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e74907af7d5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filter_excluded_guild',
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('guild_id')
    )
    op.create_table('filter_word',
    sa.Column('phrase', sa.String(), nullable=False),
    sa.Column('should_notify', sa.Boolean(), nullable=False),
    sa.Column('filter_without_removing', sa.Boolean(), nullable=True),
    sa.Column('bypass_level', sa.Integer(), nullable=False),
    sa.Column('disable_extra_checks', sa.Boolean(), nullable=True),
    sa.Column('is_piracy_phrase', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('phrase')
    )
    op.create_index('filter_word_word_index', 'filter_word', ['phrase'], unique=False)
    op.create_table('guild_setting',
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('sabbath_mode', sa.Boolean(), nullable=True),
    sa.Column('ban_today_spam', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('guild_id')
    )
    op.create_table('locked_channel',
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('channel_id')
    )
    op.create_table('logging_excluded_channel',
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('channel_id')
    )
    op.create_table('raid_phrase',
    sa.Column('phrase', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('phrase')
    )
    op.create_index('raid_phrase_word_index', 'raid_phrase', ['phrase'], unique=False)
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('is_clem', sa.Boolean(), nullable=True),
    sa.Column('was_warn_kicked', sa.Boolean(), nullable=True),
    sa.Column('is_birthday_banned', sa.Boolean(), nullable=True),
    sa.Column('is_raid_verified', sa.Boolean(), nullable=True),
    sa.Column('warn_points', sa.Integer(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('birthday', sa.String(), nullable=True),
    sa.Column('should_offline_report_ping', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index('user_user_id_index', 'user', ['user_id'], unique=False)
    op.create_table('case',
    sa.Column('case_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mod_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('BAN', 'KICK', 'MUTE', 'WARN', 'UNBAN', 'UNMUTE', 'LIFTWARN', 'REMOVEPOINTS', 'CLEM', name='casetype'), nullable=False),
    sa.Column('punishment', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('until', sa.DateTime(), nullable=True),
    sa.Column('lifted', sa.Boolean(), nullable=True),
    sa.Column('lifted_by_id', sa.Integer(), nullable=True),
    sa.Column('lifted_reason', sa.String(), nullable=True),
    sa.Column('lifted_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lifted_by_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['mod_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_index('case_case_id_index', 'case', ['case_id'], unique=False)
    op.create_index('case_user_id_index', 'case', ['user_id'], unique=False)
    op.create_table('sticky_role',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('role_id', 'user_id')
    )
    op.create_index('sticky_role_user_id_index', 'sticky_role', ['user_id'], unique=False)
    op.create_table('tag',
    sa.Column('phrase', sa.String(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('uses', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('phrase')
    )
    op.create_index('tag_name_index', 'tag', ['phrase'], unique=False)
    op.create_table('user_xp',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('is_xp_frozen', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index('user_xp_user_index', 'user_xp', ['user_id'], unique=False)
    op.create_table('tag_button',
    sa.Column('button_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tag_name', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tag_name'], ['tag.phrase'], ),
    sa.PrimaryKeyConstraint('button_id')
    )
    op.create_index('tag_button_tag_name_index', 'tag_button', ['tag_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('tag_button_tag_name_index', table_name='tag_button')
    op.drop_table('tag_button')
    op.drop_index('user_xp_user_index', table_name='user_xp')
    op.drop_table('user_xp')
    op.drop_index('tag_name_index', table_name='tag')
    op.drop_table('tag')
    op.drop_index('sticky_role_user_id_index', table_name='sticky_role')
    op.drop_table('sticky_role')
    op.drop_index('case_user_id_index', table_name='case')
    op.drop_index('case_case_id_index', table_name='case')
    op.drop_table('case')
    op.drop_index('user_user_id_index', table_name='user')
    op.drop_table('user')
    op.drop_index('raid_phrase_word_index', table_name='raid_phrase')
    op.drop_table('raid_phrase')
    op.drop_table('logging_excluded_channel')
    op.drop_table('locked_channel')
    op.drop_table('guild_setting')
    op.drop_index('filter_word_word_index', table_name='filter_word')
    op.drop_table('filter_word')
    op.drop_table('filter_excluded_guild')
    # ### end Alembic commands ###
